dist: trusty
sudo: required
language: bash
env:
  global:
  - PACKER="1.2.3"
  - TERRAFORM="0.11.7"
  - TFLINT="0.5.4"

before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-02/run.sh | bash

before_script:
- if ! packer version ; then
    wget -q -O packer.zip https://releases.hashicorp.com/packer/${PACKER}/packer_${PACKER}_linux_amd64.zip;
    sudo unzip packer.zip -d /usr/local/bin/ && rm packer.zip;
    packer version;
  fi
- if ! terraform version ; then
    wget -q -O terraform.zip https://releases.hashicorp.com/terraform/${TERRAFORM}/terraform_${TERRAFORM}_linux_amd64.zip;
    sudo unzip terraform.zip -d /usr/local/bin/ && rm terraform.zip;
    terraform version;
  fi
- if ! tflint --version ; then
    wget -q -O tflint.zip https://github.com/wata727/tflint/releases/download/v${TFLINT}/tflint_linux_amd64.zip;
    sudo unzip tflint.zip -d /usr/local/bin/ && rm tflint.zip;
    tflint --version;
  fi
- if ! ansible-lint --version ; then
    sudo pip -q install ansible-lint;
    ansible-lint --version;
  fi
- touch ~/.ssh/appuser.pub
- touch ~/.ssh/appuser

script:
- packer validate -var-file=packer/variables.json.example packer/app.json
- packer validate -var-file=packer/variables.json.example packer/db.json
- cd ./terraform/prod
- terraform init -backend=false
- terraform validate -var-file=terraform.tfvars.example
- tflint --var-file=terraform.tfvars.example
- cd - && cd ./terraform/stage
- terraform init -backend=false
- terraform validate -var-file=terraform.tfvars.example
- tflint --var-file=terraform.tfvars.example
- cd - && cd ./ansible/playbooks
- ansible-lint ./*.yml
notifications:
  slack:
    secure: Vtj69aFcGuhFhLpEyLIPGAD0wyhF5RydBwVM8kBN0RjAS07rdK9FshhXr3dLpWBAypPM9CQULbcad1gQqzoi+AY3sMW1PScinKgRZSym3/T1u/zCiYKPICSwGapH/rWu21c+WOOCa7qpwKjc2ztpSQMmvfD+hTSWzabX32xxtH2klyQSgMep0c63gnRwsVPlmi9eq+S23Ldas7ZSgZ5iEdrPmf5hGMUDAIp96CwkuoOnIRLwCd/E3xhoohiXRa8JDyWHHoTrrZhp/nNJovTem3SSaPPQvZm054SrAeiSsldJ+gYFdcFIyMFoFqiv5wkGYPyBfiSLvTWx5yThafpfFLjkPss8K7JIAdYtEtLyFsc/6viq+ssXPp4rI80r4sw1fqLftptMaZy6iJCoKlgy9F4WXGj38lKpdBTwuZUBXo1Ah2bE0DmBHbQy+tXwJjg7HSewg5/vuuTSpxNsiL5Zbp4y1gmiP+i2iQvbxSgQAgDpUAgAC3RR8xqRNRCr/QQBJ/Ccv5LexAz0uR1rGG8IJK+2+1g/BhV9Llte4HmNiNA/iV/K/aJuQ944BnbjUBavE3VwsZ2pW4OWytne++MsRjL6LrEOkdxsaxIr4XvCKBn8AWHiSNFXEyITS6s21nAEH1WeHEJ7q2qsY3l13qrAx+uRLDHjzTUKQxx6aL9m0nc=
